before_build:
    - nuget restore
branches:
  only:
    - master
build:
  project: EasyCrypto.sln
  verbosity: minimal
image: Visual Studio 2017
configuration: Debug
environment:
  COVERALL_TOKEN:
    secure: uMctBj4FhiVMESGH8OoY/Uf+6ohWcuVvPP17TqG92kAGQmqVk0ilujeeiaQjw0m0
test_script:
- ps: >-
    .\runtests.ps1